import type { Metadata } from "next";
import { Geist, Merriweather  } from "next/font/google";
import "./globals.css";
import Footer from "./components/Footer";



const merriweather = Merriweather({
   variable: "--font-merri",
  subsets: ["latin"],
  weight: ["400", "700"], 
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${merriweather.variable} ${geistSans.variable}  antialiased`}
      >
        {children}
        <Footer />
      </body>
    </html>
  );
}
